## Методы экспертных оценок

In [24]:
import numpy as np
import pandas as pd

from collections import Counter

### Определение необходимых функций

#### Метод средних рангов

In [14]:
def avg_rangs_method(data):
    """
    Функиция для ранжирования альтернатив согласно экспертным оценкам
    методом средних рангов
    
    data: матрица экспертных оценок (строки - эксперты, столбцы - альтернативы) [numpy.array]
    
    returns: массив np.array отранжированных номеров альтернатив
    """
    return np.argsort([np.average(c) for c in data.T])

#### Метод медиан рангов

In [15]:
def median_rangs_method(data):
    """
    Функиция для ранжирования альтернатив согласно экспертным оценкам
    методом медиан рангов
    
    data: матрица экспертных оценок (строки - эксперты, столбцы - альтернативы) [numpy.array]
    
    returns: массив np.array отранжированных номеров альтернатив
    """
    return np.argsort([np.median(c) for c in data.T])

#### Метод весовых коэффициентов

In [16]:
def weight_koeffs(data, weights):
    """
    Функиция для ранжирования альтернатив согласно экспертным оценкам,
    используя весовые коэффициенты.
    
    data: матрица экспертных оценок (строки - эксперты, столбцы - альтернативы) [numpy.array]
    weights: вектор весов для альтернатив [numpy.array]
    
    returns: массив np.array отранжированных номеров альтернатив
    """
    data = -data + np.max(data) + 1
    return np.argsort([np.sum(c * weights[r]) for r, c in enumerate(data.T)])

#### Подсчет коэффициента конкордации

In [17]:
def concordance_koeff(data):
    """
    Функция для определения вычисления коэффициента конкордации для
    оценки согласованности экспертов
    
    data: матрица экспертных оценок (строки - эксперты, столбцы - альтернативы) [numpy.array]
    
    returns: значение коэффициента конкордации
    """
    
    t = 0
    for row in data:
        same = Counter(row)
        for key in same:
            t += same[key] ** 3 - same[key]
        
    sum_ = np.array([np.sum(c) for c in data.T])
    deviations = np.sum((sum_.mean() - sum_) ** 2)
    m, n = data.shape
    
    result = 12 * deviations / ((m ** 2) * (n ** 3 - n) - m * t)
    return result

### Тестирование
Протестируем наши функции на данных из примера к заданию

#### Подгрузка тестовых данных

In [25]:
test_df = pd.read_csv('CvsFiles/ExpertPoints.cvs')
test_data = test_df.to_numpy()

In [26]:
test_df

a1  a2  a3  a4  a5   a6  a7  a8
0   4.5   2   2   2   8  4.5   6   7
1   8.0   7   6   3   3  3.0   3   3
2   5.0   3   1   2   8  4.0   6   7
3   5.0   3   1   2   8  4.0   6   7
4   5.0   3   1   2   8  4.0   6   7
5   5.0   3   1   2   8  4.0   6   7
6   5.0   3   1   2   8  4.0   6   7
7   5.0   3   1   2   8  4.0   6   7
8   8.0   3   1   2   5  4.0   6   7
9   2.0   3   1   5   8  4.0   6   7
10  5.0   3   1   2   8  4.0   6   7
11  5.0   3   1   2   8  4.0   6   7

In [27]:
weights = np.random.randint(1, 99, (test_data.shape[0]))
weights = weights / np.sum(weights)
mean_result = avg_rangs_method(test_data)
median_result = median_rangs_method(test_data)
weights_result = weight_koeffs(test_data, weights)
conc_koeff = concordance_koeff(test_data)

In [28]:
print(mean_result)
print(median_result)
print(weights_result)
print(conc_koeff)

[2 3 1 5 0 6 7 4]
[2 3 1 5 0 6 7 4]
[4 7 2 6 0 5 1 3]
0.7406748050186504


### Проверка на своих оценках

In [21]:
expert_count = 10
alternative_count = 8
min_rang, max_rang = 1, 8
params = {
    'low': min_rang,
    'high': max_rang,
    'size': (expert_count, alternative_count),
    'dtype': int
}

data = np.random.randint(**params)

In [22]:
weights = np.random.randint(1, 99, (data.shape[0]))
weights = weights / np.sum(weights)
mean_result = avg_rangs_method(data)
median_result = median_rangs_method(data)
weights_result = weight_koeffs(data, weights)
conc_koeff = concordance_koeff(data)

In [23]:
print(mean_result)
print(median_result)
print(weights_result)
print(conc_koeff)

[6 2 1 3 5 0 7 4]
[6 1 2 0 3 4 5 7]
[7 4 6 0 3 1 2 5]
0.0676056338028169
